### ISSUE TITLE
[Question] How to access and get a value for attributes in Conv2DOptions table in schema.fbs?

### ISSUE THREAD

**Issue by edenkim18** [SF-Zhou/tflite-model-parse#5]
Dear Zhou,

Now I try to parse and manipulate TFLite model data for studying.
Your source is very helpful to me.
But I have one question in a parsing of tflite model.

I want to get a values defined in Conv2DOptions members.
But it is related with union type, builtin_options:BuiltinOptions in Operator table,
I think it needs a different way to access to Conv2DOptions.

Would help me how I can solve this issue?

Regards,
Thank you.

**Comment by SF-Zhou** [comment]
In `schema_generated.h`, these is a function named `builtin_options_as_Conv2DOptions`. I guess this is what you want.

If you need mutable object,
```c++
auto &model = *tflite::GetMutableModel(data.data());
auto &graph_list = *model.mutable_subgraphs();
auto &graph = *graph_list.GetMutableObject(0);

auto &operators = *graph.mutable_operators();
auto &first_operator = *operators.GetMutableObject(0);
auto &conv2d_options = *static_cast<tflite::Conv2DOptions *>(first_operator.mutable_builtin_options());
```

**Comment by edenkim18** [comment]
Zhou! 
You clear my issues!! I tried a way using mutable object, but I had a problem.
My problem is no pointer in front of "static_cast".

Thank you.
